services:
  db:
    image: postgres
    restart: always
    ports:
      - '${NUXT_POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_PASSWORD: $NUXT_POSTGRES_PASSWORD
      POSTGRES_USER: $NUXT_POSTGRES_USER
      POSTGRES_DB: $NUXT_POSTGRES_DATABASE
